# Ejemplo 03
### Dr. Antonio Arista Jalife.

En este ejemplo vamos a aprender a filtrar datos por medio de máscaas de verdadero y falso. 

In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matrizBooleana = (matriz < 5)
print(matrizBooleana)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [3]:
filtro = np.array(matrizBooleana, dtype = np.int32)
print(filtro)
#con este filtro, quitamos todos los elementos mayores a 5
resultado = matriz * filtro
print("Solo los valores menores a 5:")
print(resultado)

[[1 1 1]
 [1 0 0]
 [0 0 0]]
Solo los valores menores a 5:
[[1 2 3]
 [4 0 0]
 [0 0 0]]
