# Reto 02
### Dr. Antonio Arista Jalife.

En este reto hay que generar una matriz de 10 x 10 aleatoria, y solamente conservar los valores mayores a 0.5

In [1]:
import numpy as np

In [2]:
matriz = np.random.rand(10,10)
matrizBooleana = (matriz > 0.5)
print(matrizBooleana)

[[False  True  True False False  True False False False False]
 [False False  True  True  True  True False False  True  True]
 [False False  True  True False  True False  True False  True]
 [ True  True False False  True  True  True  True  True  True]
 [ True  True False  True False  True  True False  True  True]
 [ True False False  True  True  True  True False False False]
 [False False False  True False  True  True  True  True  True]
 [ True False False False False False  True False  True False]
 [False  True False  True False  True False False False  True]
 [ True  True  True False  True  True False  True  True False]]


In [3]:
filtro = np.array(matrizBooleana, dtype = np.int32)
print(filtro)
#con este filtro, quitamos todos los elementos mayores a 5
resultado = matriz * filtro
print("Solo los valores mayores a 0.5:")
print(resultado)

[[0 1 1 0 0 1 0 0 0 0]
 [0 0 1 1 1 1 0 0 1 1]
 [0 0 1 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 1 1 1 1]
 [1 1 0 1 0 1 1 0 1 1]
 [1 0 0 1 1 1 1 0 0 0]
 [0 0 0 1 0 1 1 1 1 1]
 [1 0 0 0 0 0 1 0 1 0]
 [0 1 0 1 0 1 0 0 0 1]
 [1 1 1 0 1 1 0 1 1 0]]
Solo los valores mayores a 0.5:
[[0.         0.8188233  0.55950468 0.         0.         0.74642011
  0.         0.         0.         0.        ]
 [0.         0.         0.54972443 0.68718908 0.65793837 0.89041867
  0.         0.         0.6747728  0.88807696]
 [0.         0.         0.83551643 0.85441356 0.         0.68848865
  0.         0.93102341 0.         0.81730226]
 [0.77872646 0.87351932 0.         0.         0.70068221 0.57887281
  0.8643237  0.76868215 0.86252066 0.59873808]
 [0.648172   0.8544594  0.         0.8603441  0.         0.71738537
  0.52822337 0.         0.99948014 0.86157773]
 [0.63387942 0.         0.         0.90441096 0.92675149 0.94392576
  0.89702509 0.         0.         0.        ]
 [0.         0.         0.         0.77443237 0

In [5]:
matriz[matrizBooleana]

array([0.8188233 , 0.55950468, 0.74642011, 0.54972443, 0.68718908,
       0.65793837, 0.89041867, 0.6747728 , 0.88807696, 0.83551643,
       0.85441356, 0.68848865, 0.93102341, 0.81730226, 0.77872646,
       0.87351932, 0.70068221, 0.57887281, 0.8643237 , 0.76868215,
       0.86252066, 0.59873808, 0.648172  , 0.8544594 , 0.8603441 ,
       0.71738537, 0.52822337, 0.99948014, 0.86157773, 0.63387942,
       0.90441096, 0.92675149, 0.94392576, 0.89702509, 0.77443237,
       0.56990112, 0.94691842, 0.78163409, 0.56777209, 0.96606568,
       0.89286724, 0.81689258, 0.89485058, 0.71407979, 0.89717438,
       0.81525723, 0.60308722, 0.88604883, 0.94906682, 0.63935018,
       0.99434074, 0.74496956, 0.86736306, 0.50036924])

In [6]:
resultado[resultado>0]

array([0.8188233 , 0.55950468, 0.74642011, 0.54972443, 0.68718908,
       0.65793837, 0.89041867, 0.6747728 , 0.88807696, 0.83551643,
       0.85441356, 0.68848865, 0.93102341, 0.81730226, 0.77872646,
       0.87351932, 0.70068221, 0.57887281, 0.8643237 , 0.76868215,
       0.86252066, 0.59873808, 0.648172  , 0.8544594 , 0.8603441 ,
       0.71738537, 0.52822337, 0.99948014, 0.86157773, 0.63387942,
       0.90441096, 0.92675149, 0.94392576, 0.89702509, 0.77443237,
       0.56990112, 0.94691842, 0.78163409, 0.56777209, 0.96606568,
       0.89286724, 0.81689258, 0.89485058, 0.71407979, 0.89717438,
       0.81525723, 0.60308722, 0.88604883, 0.94906682, 0.63935018,
       0.99434074, 0.74496956, 0.86736306, 0.50036924])